### PR TITLE
Add get kamino positions to sdk

### PR DESCRIPTION
**Pull request by peroxy**
Returns something like this:

```
      {
        shareMint: 'DcLcLcZsdMRrHo87CJPP4eagiMiFSDuKehkPeiQYSnXn',
        strategy: '7KqB3vRJQDdGwK7ewiDpAxXpTeMmgGicdDdbftQH41XC',
        sharesAmount: '14.459498'
      },
      {
        shareMint: '5BmZgW7dk1kximGfn7MPvDigp3yRmgT64jS9Skdq4nPY',
        strategy: 'Cfuy5T6osdazUeLego5LFycBQebm9PP3H7VNdCndXXEN',
        sharesAmount: '6.604654'
      }
```

### CODE REVIEW

**Review by elliotkennedy — APPROVED** [review]
Looks good - some small thoughts -

- This is a very heavy call
- spl-token-2022 will have  new program id when it is deployed
- TOKEN_PROGRAM_ID - is available as a constant in the spl-token lib

**Comment by peroxy** [comment]
> Looks good - some small thoughts -
> 
>     * This is a very heavy call
> 
>     * spl-token-2022 will have  new program id when it is deployed
> 
>     * TOKEN_PROGRAM_ID - is available as a constant in the spl-token lib

Ah, you're absolutely right - will use the TOKEN_PROGRAM_ID constant.

Regarding being a very heavy call, what do you mean exactly? Do you have an alternative in mind?

**Comment by elliotkennedy** [comment]
> 

It depends where the call is being used but I think it will be ok for a first pass - will have a think if it can be done better

Someone explained to me that the issue with too many getProgramAccounts calls is that it is so heavy it can cause the RPC nodes to fall behind if you overuse it

**Comment by peroxy** [comment]
@elliotkennedy 
> > 
> 
> It depends where the call is being used but I think it will be ok for a first pass - will have a think if it can be done better
> 
> Someone explained to me that the issue with too many getProgramAccounts calls is that it is so heavy it can cause the RPC nodes to fall behind if you overuse it

Interesting - for now, this will be used by external aggregators that show the user's position, think Sonarwatch or Step finance.

**Comment by elliotkennedy** [comment]
> 

No worries then - we will see if they complain! :)

**Comment by peroxy** [comment]
Reasonable and pragmatic :smile: 

Will keep it in mind though, thanks for the comments.

**Comment by elliotkennedy** [comment]
> Reasonable and pragmatic :smile: 
> 
> Will keep it in mind though, thanks for the comments.

https://solanacookbook.com/guides/get-program-accounts.html#dataslice

Looks like your impl is perfect 👍

**Comment by peroxy** [comment]
Nice, glad to hear it!

**Pull request merged**
